[package]
name = "mdbook-nix-repl"
version = "0.6.9"
edition = "2024"
authors = ["T. Sawyer saylesss88@github.com"]
license = "Apache-2.0"
description = "An mdBook preprocessor to provide nix-repl functionality within mdbook"
repository = "https://github.com/saylesss88/mdbook-nix-repl"
readme = "README.md"
keywords = ["mdbook", "nix", "repl", "preprocessor"]
categories = [
	"command-line-utilities",
	"development-tools::build-utils",
	"web-programming",
]
homepage = "https://github.com/saylesss88/mdbook-nix-repl"
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md",
	"LICENSE",
	"theme/nix_http.js",
	"server/Cargo.toml.inc",
	"server/Dockerfile",
	"server/src/**/*",
]

[dependencies]
mdbook-preprocessor = "0.5.3"
anyhow = {version = "1.0", default-features = false}
env_logger = {version = "0.11", default-features = false}
serde = {version = "1.0", default-features = false}
serde_json = "1.0"
html-escape = {version = "0.2", default-features = false}
semver = "1.0"
clap = {version = "4", features = ["derive"]}
rand = {version = "0.10.2", features = ["sys_rng"], default-features = false}
hex = {version = "0.4.3", features = ["alloc"], default-features = false}
toml = {version = "1.1.2", default-features = false}
url = {version = "2.5", default-features = false}

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[lints.rust]
unsafe_code = "forbid"
future_incompatible = {level = "warn", priority = -1}
nonstandard_style = {level = "warn", priority = -1}
rust_2018_idioms = {level = "warn", priority = -1}

[lints.rustdoc]
all = "warn"
missing_crate_level_docs = "warn"

[lints.clippy]
all = {level = "warn", priority = -1}
pedantic = {level = "warn", priority = -1}
todo = "warn"
dbg_macro = "warn"
unwrap_used = "warn"
